---
title: "Qtools Vignette"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Qtools Vignette}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```



```{r, echo=TRUE, eval=FALSE}

library(tidyverse)
library(knitr)
library(haven)
library(Qtools)

# Creates raw, out, and pst folders
new_proj()

# Basic frequency tab
frtab(infert, Education)

# Basic crosstab
ctab(infert, Education, induced)

# Codebook crosstab - Uses col number: 1=education.
cbtab(infert, 1)

# CATA frequency table that shows % selected and removes question stub text
catatab(df, "Q15", "What is your race? Selected option ")

# Create a codebook from a Qualtrics data file

### Load data from SPSS formatted file

df <- read_spss("./EXAMPLE SURVEY DATA.sav")

### Remove paradata and keep survey data
### Replace A and Z with first and last variable

df <- df %>% select(csid = ExternalReference, Q_A:Q_Z)

### Create a list of all variables and check their type.
### Character variables start with an 'A'

varlist <- tibble(
  var = names(df),
  labels = map_chr(1:ncol(df), function(x) attr(df[[x]], "label")),
  typ = map_chr(1:ncol(df), function(x) attr(df[[x]], "format.spss")),
  oe = str_detect(typ, "A")
)

### Separate OE vars 

oev <- varlist %>% filter(oe == TRUE)
varlist <- varlist %>% filter(oe == FALSE)

oe <- df %>% select(oev$var)
df <- df %>% select(varlist$var)

### Apply variable and value labels

df <- as_factor(df)

### Specify file name for frequency report and create the template

codebk("Example Data Frequency Report.qmd", df, varlist)

### Export comments to separate files with date stamp
### Example exported file name: P9999 Q45_TEXT Responses 2022-10-12.csv

for(i in 1:length(names(oe))) {
  openend(oe, i, "P9999")
}


```



```
